name: Auto-Merge on Comment

on:
  issue_comment:
    types:
      - created

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Comment
        id: check_comment
        run: echo "Checking for the specific comment..."

      - name: Check Comment Content and Email
        id: check_comment_content
        run: |
          # Define an array of allowed email addresses
          allowed_emails=("thiyagaraj0" "thiyagaraj0@gmail.com" "another@example.com")
          allowed_comments=("approved" "approve" "yes")

          # Check if the comment contains "approve" or "approved" and if the commenter's email is in the array of allowed emails
          lowercase_comment=$(echo "${{ github.event.comment.body }}" | awk '{print tolower($0)}' )
          
          # Trim spaces using tr
          trimmed_comment=$(echo "$lowercase_comment" | tr -d ' ')

          # Check if the comment contains "approve" or "approved" and if the commenter's email is in the array of allowed emails
          lowercase_email=$(echo "${{ github.event.comment.user.login }}" | awk '{print tolower($0)}' )
          
          # Trim spaces using tr
          trimmed_email=$(echo "$lowercase_email" | tr -d ' ')

          echo "trimmed_email $trimmed_email"
          if [[ " ${allowed_comments[@]} " =~ " ${trimmed_comment} " ]]; then
            if [[ " ${allowed_emails[@]} " =~ " ${trimmed_email} " ]]; then
              echo "Comment contains the trigger phrase, and the email is allowed."
            else
              echo "Comment contains the trigger phrase, but the email is not allowed. Exiting..."
              exit 1
            fi
          else
            echo "Comment does not meet the criteria. Exiting..."
            exit 1
          fi

      - name: Merge Main to Dev
        if: success() # Only proceed if the comment meets the criteria
        run: |
          # Merge main branch into dev branch
          git checkout dev
          git pull origin main
          git push origin dev

      - name: Merge Main to UAT
        if: success() # Only proceed if the comment meets the criteria
        run: |
          # Merge main branch into uat branch
          git checkout uat
          git pull origin main
          git push origin uat
