name: Execute Script on Master Push

on:
  push:
    branches:
      - master

jobs:
    approve_then_deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Approve and then deploy
            uses: trstringer/manual-approval@v1
            with:
              secret: "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"
              approvers: Thiyagaraj0,user2,user3
              minimum-approvals: 1
              issue-title: "Deploying v1.3.5 to prod from staging"
              issue-body: "Please approve or deny the deployment of version v1.3.5."
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: ''
