name: Create GitHub Issue and Wait for Comment
on:
  push:
    branches:
      - master

jobs:
  create-issue-and-wait:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check out code
      run: |
        echo "Creating new issue..."
        cat ISSUE_TEMPLATE.md | sed -e "s/{{title}}/$GITHUB_EVENT_TITLE/" | sed -e "s/{{body}}/$GITHUB_EVENT_BODY/" | github-issue create

    - name: Wait for Comment
      id: wait_for_comment
      run: |
        while true; do
          comments=$(curl -s -H "Authorization: token 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" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.create_issue.outputs.issue_number }}/comments")
          if echo "$comments" | jq -e 'any(.[].user.login == "YOUR_USERNAME" and (.body | test("approved?"; "i"))) or (.user.email | in("allowed_email_1", "allowed_email_2"))' > /dev/null; then
            echo "Comment found."
            break
          fi
          echo "Comment not found. Waiting..."
          sleep 60
        done

    - name: Push to Dev and UAT
      if: success()
      run: |
        git checkout -b dev
        git pull origin main
        git push origin dev

        git checkout -b uat
        git pull origin main
        git push origin uat
