name: Create Issue on Push

on:
  push:
    branches:
      - master  # Replace with the branch you want to trigger the issue creation

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Issue
        id: create_issue
        run: |
          # Replace with your desired issue title and body
          issue_title="New Push Detected"
          issue_body="A new push has been made to the repository."

          # Create the issue using the GitHub API
          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"title\":\"$issue_title\",\"body\":\"$issue_body\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues")

          # Extract the issue number from the response
          issue_number=$(echo $response | jq -r .number)

          # Store the issue number as an output for future use
          echo "::set-output name=issue_number::$issue_number"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Issue Created
        run: echo "Issue ${{ steps.create_issue.outputs.issue_number }} has been created."
